services:
  - type: web
    name: secret-santa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      SUPABASE_URL: https://noqqsyadhxevnptstorf.supabase.co
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcXFzeWFkaHhldm5wdHN0b3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxODc1MzcsImV4cCI6MjA3Nzc2MzUzN30.swFNi6fwkiA1-nQeKfMB8xji9s4h9E3ihtRcCgIWTac
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcXFzeWFkaHhldm5wdHN0b3JmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjE4NzUzNywiZXhwIjoyMDc3NzYzNTM3fQ.5BEefg-orT7E1F0MvmDIkq9PvLUOb8fXWuroJIfRN84